### PR TITLE
Use ifconfig.me instead of Jeedom cloud

### PR DESCRIPTION
**Pull request by tuxgasy**

### CODE REVIEW

**Comment by zoic21** [comment]
Hello,
Why ? If we used cloud jeedom it's because we are sure that this service don't register information or keep it.

**Comment by tuxgasy** [comment]
I have a lot of errors with cloud jeedom.

**Comment by zoic21** [comment]
Can you give me this error ? With that maybe I can fix it (specially if it's quota)

**Comment by tuxgasy** [comment]
Usually, I got the following error
`Erreur lors de la requete au serveur cloud Jeedom : {"state":"nok","error":"Quotas exceeded"}`
I'm definitely over the limit. What is the limit ?

Rarely, I have another error but I can no longer find it in the log.

**Comment by zoic21** [comment]
Yestarday limit was 1 call by 5min. I change this night for 5 calls by 1min (and now error message indicate the limit).

**Comment by tuxgasy** [comment]
Ok thanks.

**Pull request closed without merging**
